# appveyor.yml
image: Visual Studio 2019

install:
  - set PATH=C:\Ruby26\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

platform:
  - x64

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
    - generator: "Visual Studio 16 2019"

matrix:
  fast_finish: true

test_script:
  - bundle exec rake compile && bundle exec rake test
  # test pure ruby fallback code
  - cmd /V /C "set FAST_OSC_USE_FALLBACK=true" && bundle exec rake test
